from enum import Enum


class Icon(Enum):
    """
    Enum of icon image paths.
    """

    ALERT_CIRCLE_FILLED = "_resources/dark_theme/alert-circle-filled.svg"
    BACK_BUTTON = "_resources/dark_theme/back.svg"
    BOUNDING_BOX = "_resources/dark_theme/bbox.svg"
    CANCEL_CIRCLE = "_resources/dark_theme/270-cancel-circle.svg"
    CHECKED = "_resources/dark_theme/checked.svg"
    CHECKED_CIRCLE_FILLED = "_resources/dark_theme/checked-circle-filled.svg"
    CROSS2_SIGN = "_resources/dark_theme/1134-cross2.svg"
    CROSS_CIRCLE_FILLED = "_resources/dark_theme/cross-circle-filled.svg"
    DELETE = "_resources/dark_theme/delete.svg"
    DOWN_ARROW = "_resources/dark_theme/1217-arrow-down2.svg"
    DOWNLOAD = "_resources/dark_theme/download.svg"
    EQUALIZER = "_resources/dark_theme/0604-equalizer.svg"
    INFO_CIRCLE_FILLED = "_resources/dark_theme/info-circle-filled.svg"
    KEY = "_resources/dark_theme/142-key.svg"
    LEFT_ARROW = "_resources/dark_theme/chevron-left.svg"
    LIGHTNING = "_resources/dark_theme/0842-power2.svg"
    MOON = "_resources/light_theme/moon.svg"
    MOVE = "_resources/dark_theme/arrow-turn-down-right.svg"
    NEGATIVE = "_resources/dark_theme/negative-icon.svg"
    RED_CROSS = "_resources/dark_theme/red-cross.svg"
    PLUS = "_resources/dark_theme/plus.svg"
    POLYGON = "_resources/dark_theme/polygon.svg"
    PROFILE = "_resources/dark_theme/036-profile.svg"
    RADIO_BUTTON_CHECKED = "_resources/dark_theme/radio-checked-dark.svg"
    RADIO_BUTTON_CHECKED_LIGHT = "_resources/light_theme/1394-radio-checked.svg"
    RADIO_BUTTON_UNCHECKED = "_resources/dark_theme/radio-unchecked-dark.svg"
    RADIO_BUTTON_UNCHECKED_LIGHT = "_resources/light_theme/1396-radio-unchecked.svg"
    RESET = "_resources/dark_theme/reset-svgrepo-com.svg"
    RIGHT_ARROW = "_resources/dark_theme/chevron-right.svg"
    ROI_WINDOWING = "_resources/dark_theme/0049-gradient.svg"
    SAVE = "_resources/dark_theme/floppy-disk.svg"
    SEARCH = "_resources/dark_theme/0567-search3.svg"
    SUN = "_resources/dark_theme/sun.svg"
    SYNC = "_resources/dark_theme/cloud-sync.svg"
    TRASH = "_resources/dark_theme/trash_dark_theme.svg"
    UPLOAD = "_resources/dark_theme/upload.svg"
    USER = "_resources/dark_theme/114-user.svg"

    LOGIN_BG = "_resources/dark_theme/background-image.png"
    SPLASH_SCREEN_BG = "_resources/dark_theme/splash-screen-bg.svg"
